spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-auth
    username: postgres
    password: 10022000a
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernates:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect